name: nightly-release

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          USERNAME: MaxChangInnodisk
          token: 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
          submodules: true

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-nightly.zip ${{ github.event.repository.name }} -r
          
      - uses: pyTooling/Actions/releaser@r0
        with:
          USERNAME: MaxChangInnodisk
          token: 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
          tag: nightly
          files: ${{ github.event.repository.name }}-nightly.zip
