name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Submodule
        uses: actions/checkout@v2
        with:
          token: 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
          submodules: true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-${{ steps.get_version.outputs.VERSION }}.zip -r ${{ github.event.repository.name }}
      
      - name: Release Repository  
        uses: pyTooling/Actions/releaser@r0
        with:
          USERNAME: ${{ secrets.USERNAME }}
          token: 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
          tag: ${{ steps.get_version.outputs.VERSION }}
          files: ${{ github.event.repository.name }}-${{ steps.get_version.outputs.VERSION }}.zip